#!/usr/bin/env bash
INSTALL_PATH="/tmp/noti-notify"
git clone "https://github.com/rhuan-pk/noti-notify.git" ${INSTALL_PATH}
mkdir -p /usr/local/bin/noti-notify
sudo mv ${INSTALL_PATH}/lib/* /usr/local/lib/noti-notify
sudo mv ${INSTALL_PATH}/bin/* /usr/local/bin
rm -rf ${INSTALL_PATH}
